packages:
  - "./src/types"
  - "./src/constants"
  - "./src/utils"
  - "./src/styles"
  - "./src/localization"
  - "./src/deckgl-layers"
  - "./src/layers"
  - "./src/schemas"
  - "./src/table"
  - "./src/cloud-providers"
  - "./src/processors"
  - "./src/tasks"
  - "./src/actions"
  - "./src/reducers"
  - "./src/components"
  - "./examples/demo-app"
  - "./examples/custom-map-style"
